### ISSUE TITLE
Spark charm missing in CharmHub

### ISSUE THREAD

**Issue by Barteus** [canonical/spark-operator#10]
When searching for spark charm in CharmHub there is none for Kubernetes available. 

![image](https://user-images.githubusercontent.com/20493786/154493592-f167a3e6-76ac-4301-92f0-4af35b2a7fd3.png)

You can deploy it using: `juju deploy ch:spark` If this charm should be deployed like this then please adjust the README.

**Comment by DomFleischmann** [comment]
This is now fixed. This spark operator is now available under the name `spark-k8s` in charmhub.
