### ISSUE TITLE
Charm uses the “prometheus” relation interface

### ISSUE THREAD

**Issue by mmanciop** [canonical/spark-operator#8]
https://github.com/canonical/spark-operator/blob/e66a63d08f41acfa8fce7401f2b0624ddbbf1632/metadata.yaml#L24

Since a few months we changed the relation interface name to be more descriptive, and in doing so, we consciously broke backwards compatibility. This issue is for upgrading the support in the Spark charm to the [prometheus_scrape](https://charmhub.io/prometheus-k8s/libraries/prometheus_scrape) library.

**Comment by averma-canonical** [comment]
Hi @agathanatasha , can I close this?
